"""Add trip_group_messages table

Revision ID: 2bde7ac4d7e0
Revises: chat_001_add_messages
Create Date: 2025-11-25 00:31:29.752772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bde7ac4d7e0'
down_revision: Union[str, None] = 'chat_001_add_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_group_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_group_messages_sender_id'), 'trip_group_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_trip_group_messages_trip_id'), 'trip_group_messages', ['trip_id'], unique=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'confirmed', 'canceled', name='bookingstatus'),
               existing_nullable=False)
    op.drop_index('ix_bookings_passenger_id', table_name='bookings')
    op.drop_index('ix_bookings_ride_id', table_name='bookings')
    op.drop_index('ix_favorite_rides_user_id', table_name='favorite_rides')
    op.drop_index('ix_ratings_booking_id', table_name='ratings')
    op.drop_index('ix_ratings_rated_id', table_name='ratings')
    op.drop_index('ix_ratings_rater_id', table_name='ratings')
    op.drop_index('ix_rides_driver_id', table_name='rides')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.create_index('ix_ratings_rater_id', 'ratings', ['rater_id'], unique=False)
    op.create_index('ix_ratings_rated_id', 'ratings', ['rated_id'], unique=False)
    op.create_index('ix_ratings_booking_id', 'ratings', ['booking_id'], unique=False)
    op.create_index('ix_favorite_rides_user_id', 'favorite_rides', ['user_id'], unique=False)
    op.create_index('ix_bookings_ride_id', 'bookings', ['ride_id'], unique=False)
    op.create_index('ix_bookings_passenger_id', 'bookings', ['passenger_id'], unique=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'canceled', name='bookingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_trip_group_messages_trip_id'), table_name='trip_group_messages')
    op.drop_index(op.f('ix_trip_group_messages_sender_id'), table_name='trip_group_messages')
    op.drop_table('trip_group_messages')
    # ### end Alembic commands ###
