name: Build & Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r backend/requirements.txt -r backend/requirements-dev.txt
      - name: Lint
        run: |
          ruff check backend/
          black --check backend/
      - name: Test
        run: pytest backend/tests
