name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint
        run: |
          ruff --version
          ruff check .
          black --check .

      - name: Test
        env:
          # Evita necesitar Postgres en CI. Nuestro test de salud no toca BBDD.
          DATABASE_URL: "sqlite+pysqlite:///:memory:"
          SECRET_KEY: "dummy"
          ACCESS_TOKEN_EXPIRE_MINUTES: "60"
          EMAIL_CODE_EXPIRE_MINUTES: "15"
          ALLOWED_EMAIL_DOMAINS: "ugr.es"
          MAIL_FROM: "unigo@dev.local"
          MAIL_PORT: "1025"
          MAIL_SERVER: "127.0.0.1"
          MAIL_STARTTLS: "False"
          MAIL_SSL_TLS: "False"
        run: pytest -q
